[project]
name = "procon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.10"
dependencies = [
    "fabric>=3.2.2",
    "pyyaml>=6.0.2",
    "watchdog>=4.0.2",
]
